#FROM jairamc/spark-kafka-streaming
FROM nopponaim603/spark-streaming-kafka

# Pip
RUN apt-get -y update && \
    apt-get -y install python3-pip && \
    pip3 install --upgrade pip


# Notebook

RUN pip --no-cache-dir install jupyter

# Apache Toree: Scala kernal for the Jupyter Notebook
# https://toree.apache.org/
#RUN cd /tmp && \
#    wget https://dlcdn.apache.org/incubator/toree/0.4.0-incubating/toree/toree-0.4.0-incubating-bin.tar.gz && \
COPY ./toree-0.2.0.dev1.tar.gz /tmp/
#COPY ./toree-0.4.0.tar.gz /tmp/

RUN pip --no-cache-dir install /tmp/toree-0.2.0.dev1.tar.gz && \
    jupyter toree install

EXPOSE 8888
